source 'https://rubygems.org'
ruby '2.0.0'
gem 'rails', '4.0.2'
gem 'rails_12factor', group: :production
gem 'newrelic_rpm'
gem 'pg'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'figaro'
gem 'foundation-rails'
gem 'high_voltage'
gem 'simple_form'
gem 'slim-rails'
gem 'unicorn'
gem 'unicorn-rails'
group :development do
  gem 'better_errors'
  gem 'binding_of_caller', :platforms=>[:mri_19, :mri_20, :rbx]
  gem 'quiet_assets'
  gem 'rails_layout'
end
